-- Copyright (c) 2026 Martin Rinard
import Generated.Seam.lcm.ValidExtremal

/-!
# `LCM.LcmAdapter` — the `LcmSpec` validity bundle (adapter over the generated interface).

The six per-ghost facts — `Anticipated`/`Available`/`Postponable`/`Used` (generated clause predicates)
and the two `Transfer` confluence relations (τₚ meet of ηₚ, τᵤ join of πᵤ; generic, in `LcmDefs`) — plus
the solver and the uniform `LCMResult`/`Valid`/`Extremal` interface are all GENERATED by `gen` from
`Lcm.gsl` (see `Seam/lcm/ValidExtremal.lean`); the node-local defs + placements they read are authored in
`LcmDefs.lean`. This file is the thin **adapter** the verified transform consumes: `LcmSpec` (the
six-ghost bundle + validity witnesses) and its `Extremal` predicate, stated over the generated
predicates. Downstream of the generated interface.

The ~14 LCM proof files import this for `LcmSpec`/`Extremal` — and, transitively, the generated
ghost predicates + defs/placements.
-/

namespace BaseLanguage.Analyses.LCM
open Tac Semantics Std

structure LcmSpec (P : Program) where
  πₐ    : Node → Assignments
  ηₐ   : Node → Assignments
  ηₚ   : Node → Assignments
  τₚ    : Node → Assignments
  πᵤ    : Node → Assignments
  τᵤ : Node → Assignments
  isAnti    : Anticipated P πₐ
  isAvail   : Available P ηₐ
  isPostp   : Postponable P πₐ ηₐ ηₚ
  isTauP    : Transfer Assignments.Subset P ηₚ τₚ
  isUsed    : Used P (latestNode P ηₚ τₚ) (latestEdge P πₐ ηₐ ηₚ) πᵤ
  isUsedOut : Transfer Assignments.Sup P πᵤ τᵤ

structure Extremal {P : Program} (S : LcmSpec P) : Prop where
  πₐ    : ∀ g, Anticipated P g → ∀ n, (g n).Subset (S.πₐ n)
  ηₐ   : ∀ g, Available P g → ∀ n, (g n).Subset (S.ηₐ n)
  ηₚ   : ∀ g, Postponable P S.πₐ S.ηₐ g → ∀ n, (g n).Subset (S.ηₚ n)
  τₚ    : ∀ g, Transfer Assignments.Subset P S.ηₚ g → ∀ n, (g n).Subset (S.τₚ n)
  πᵤ    : ∀ g, Used P (latestNode P S.ηₚ S.τₚ) (latestEdge P S.πₐ S.ηₐ S.ηₚ) g → ∀ n, (S.πᵤ n).Subset (g n)
  τᵤ : ∀ g, Transfer Assignments.Sup P S.πᵤ g → ∀ n, (S.τᵤ n).Subset (g n)

end BaseLanguage.Analyses.LCM
