-- Copyright (c) 2026 Martin Rinard
import Generated.Seam.pdce.ValidExtremal

/-!
# `PDCE.PdceAdapter` — the `PdceSpec` validity bundle (adapter over the generated interface).

The ghost predicates `Live`/`Sink`, the solver, and the uniform `PDCEResult`/`Valid`/`Extremal` interface
are GENERATED by `gen` from `Pdce.gsl` (see `Seam/pdce/ValidExtremal.lean`); the node-local defs
they read are authored in `PdceDefs.lean`. This file is the thin **adapter** the verified transform
consumes: `PdceSpec` (the `π`/`η` bundle + `Live`/`Sink` witnesses) and its `Extremal` predicate, both
stated over the generated `Live`/`Sink`. Downstream of the generated interface.

The ~20 PDCE proof files import this for `PdceSpec`/`Extremal` — and, transitively, the generated
`Live`/`Sink` + the defs.
-/

namespace BaseLanguage.Analyses.PDCE
open Tac Semantics Std

-- validity bundle: ghosts first, then the `isFam` validity witnesses (over the generated `Live`/`Sink`)
structure PdceSpec (P : Program) where
  π   : Node → Variables
  η   : Node → Assignments
  isLive : Live P π
  isSink : Sink P η

-- extremality predicate: `least π` ⇒ S.π ⊑ any valid g ; `greatest η` ⇒ any valid g ⊑ S.η
structure Extremal {P : Program} (S : PdceSpec P) : Prop where
  π : ∀ g, Live P g → ∀ n, (S.π n).Subset (g n)
  η : ∀ g, Sink P g → ∀ n, (g n).Subset (S.η n)

end BaseLanguage.Analyses.PDCE
