-- Copyright (c) 2026 Martin Rinard
import BaseLanguage.IR.LocalsSub
import BaseLanguage.Behavior.Outcomes
/-!
# `Pass.BranchFold` — fold a branch whose condition is a known constant.

Runs on an abstract **`CPSpec`** — a validity + extremality bundle for a constant-propagation solution,
stated purely over `Step` and the CP leaves (`genConst`/`transpConst`), with no reference to the solver,
its fixpoint, or its term calculus. Any valid+extremal CP solution instantiates it; the generated
`cpSol`/`cp_correct` is one instance (wired in `generated/constprop/Adapter`, the sole solver coupling).

**Soundness kernel (`CPInv`).** The store at every reachable configuration satisfies the CP facts there
(`⟨x,c⟩ ∈ sol n → store x = c`): the entry has no facts (`seed`), and each `Step` preserves the invariant
(a fact is either freshly generated by `x := imm c` — so the assign sets `x := c` — or carried and
transparent — so `x` is not redefined and keeps its value).

**Transform.** At `ifz x z nz` where `⟨x,c⟩` is a known constant, rewrite to `noop z` (`c = 0`) or
`noop nz` (`c ≠ 0`). Because `CPInv` forces `store x = c` there, the original `ifzT`/`ifzF` step goes to
exactly the target the `noop` goes to — so the rewrite preserves halt/fault/diverge. The orphaned subtree
is then removed by `Pass.UCE`.
-/
namespace BaseLanguage
namespace Pass
namespace BranchFold

open Tac Tac.Locals Semantics Std

variable {P : Program}

/-- **Constant-propagation validity** — the fwd·must reaching clauses over `Step`, in the CP-leaf shape the
    generator's `ConstPropClauses` emits (this is the clean, solver-free predicate; the adapter bridges the
    two by defeq). -/
structure CPValid (P : Program) (cp : Node → ConstPairs) : Prop where
  update : ∀ {c c' : Config}, Step P c c' →
             (cp c'.node).Subset ((genConst P c.node).union ((cp c.node).inter (transpConst P c.node)))
  seed   : (cp P.entry).Subset ConstPairs.empty
  within : ∀ n, (cp n).Subset (allConst P)

/-- **Abstract constant-propagation solution** — validity + extremality (greatest, for fwd·must). Any such
    solution instantiates it; the generated `cpSol` is one. -/
structure CPSpec (P : Program) where
  sol      : Node → ConstPairs
  valid    : CPValid P sol
  greatest : ∀ g, CPValid P g → ∀ n, (g n).Subset (sol n)

variable (S : CPSpec P)

/-! ## The soundness invariant. -/

/-- The store at `c` agrees with every constant fact the solution holds at `c.node`. -/
def CPInv (c : Config) : Prop := ∀ x v, (x, v) ∈ S.sol c.node → c.store x = v

theorem cpInv_entry {σ : Store} : CPInv S ⟨P.entry, σ⟩ := by
  intro x v hmem; exact absurd (S.valid.seed (x, v) hmem) Std.HashSet.not_mem_empty

/-- A `genConst` fact identifies the node as the matching literal copy. -/
theorem mem_genConst {n : Node} {p : CPair} (h : p ∈ genConst P n) :
    ∃ nx, P.fetch n = some (.assign p.1 (.atom (.imm p.2)) nx) := by
  unfold genConst at h
  split at h
  · next y d nx heq =>
      have hp := ConstPairs.mem_singleton.mp h; subst hp; exact ⟨nx, heq⟩
  · exact absurd h Std.HashSet.not_mem_empty

/-- **`CPInv` is preserved by every step** — the analysis⇒semantics bridge for constant propagation. -/
theorem cpInv_step {c c' : Config} (hinv : CPInv S c) (h : Step P c c') : CPInv S c' := by
  intro x v hmem
  rcases ConstPairs.mem_union.mp (S.valid.update h (x, v) hmem) with hgen | hint
  · -- freshly generated: `c.node` is `assign x (imm v)`, and the step sets `x := v`
    obtain ⟨nx, hfetch⟩ := mem_genConst hgen
    cases h with
    | @assign nd σ y e next w hf hev =>
        rw [hf] at hfetch; injection hfetch with hc; injection hc with e1 e2 e3
        subst e1; subst e2
        simp only [eval, evalAtom, Option.some.injEq] at hev
        show (σ.update y w) y = v; rw [Store.update, if_pos rfl]; exact hev.symm
    | ifzT hf _ => rw [hf] at hfetch; simp at hfetch
    | ifzF hf _ => rw [hf] at hfetch; simp at hfetch
    | noop hf => rw [hf] at hfetch; simp at hfetch
  · -- carried through transparently: `x = v` before (IH), and `c.node` does not redefine `x`
    rw [ConstPairs.mem_inter] at hint
    have hpre : c.store x = v := hinv x v hint.1
    have hnd : definedVar P c.node ≠ some x := by
      have h2 := (ConstPairs.mem_filter'.mp hint.2).2; simpa [bne_iff_ne] using h2
    cases h with
    | @assign nd σ y e next w hf hev =>
        have hyx : y ≠ x := fun heq => hnd (by simp [definedVar, hf, instrDefVar, heq])
        show (σ.update y w) x = v; rw [Store.update, if_neg hyx.symm]; exact hpre
    | ifzT hf _ => exact hpre
    | ifzF hf _ => exact hpre
    | noop hf => exact hpre

/-- Every configuration reached from the entry satisfies `CPInv`. -/
theorem cpInv_run {σ : Store} {c : Config} (h : Steps P ⟨P.entry, σ⟩ c) : CPInv S c := by
  induction h with
  | refl => exact cpInv_entry S
  | tail _ hst ih => exact cpInv_step S ih hst

/-! ## The transform. -/

/-- The constant `sol n` assigns to `x`, if any (must ⇒ at most one). -/
def constAt (n : Node) (x : Var) : Option Val := ((S.sol n).toList.find? (fun p => p.1 == x)).map (·.2)

theorem constAt_sound {n : Node} {x : Var} {c : Val} (h : constAt S n x = some c) : (x, c) ∈ S.sol n := by
  unfold constAt at h
  cases hf : (S.sol n).toList.find? (fun p => p.1 == x) with
  | none => rw [hf] at h; simp at h
  | some p =>
      rw [hf] at h; simp only [Option.map_some, Option.some.injEq] at h; subst h
      have hx : p.1 = x := by simpa using List.find?_some hf
      have hin : p ∈ (S.sol n).toList := List.mem_of_find?_eq_some hf
      rw [show (x, p.2) = p from by rw [← hx]]; exact Std.HashSet.mem_toList.mp hin

/-- Fold a determined branch; carry every other instruction verbatim. -/
def foldCmd (n : Node) : Cmd → Cmd
  | .ifz x z nz => match constAt S n x with
                   | some c => if c == 0 then .noop z else .noop nz
                   | none   => .ifz x z nz
  | other       => other

/-- Every successor of a folded instruction was a successor of the original. -/
theorem foldCmd_mem_succs {n : Node} {c : Cmd} {s : Node} (h : s ∈ (foldCmd S n c).succs) :
    s ∈ c.succs := by
  cases c with
  | ifz x z nz =>
      simp only [foldCmd] at h
      split at h
      · split at h <;>
          (simp only [Cmd.succs, List.mem_singleton] at h; subst h; simp [Cmd.succs])
      · exact h
  | _ => exact h

/-- **Branch-folding.** -/
def run (P : Program) (S : CPSpec P) : Program where
  entry := P.entry
  code  := ((List.range P.size).map (fun n => foldCmd S n ((P.fetch n).getD .halt))).toArray
  obs   := P.obs

@[simp] theorem run_entry (P : Program) (S : CPSpec P) : (run P S).entry = P.entry := rfl
@[simp] theorem run_obs (P : Program) (S : CPSpec P) : (run P S).obs = P.obs := rfl
@[simp] theorem run_size (P : Program) (S : CPSpec P) : (run P S).size = P.size := by
  show ((List.range P.size).map _).toArray.size = P.size; simp

theorem run_fetch {n : Node} (h : n < P.size) :
    (run P S).fetch n = some (foldCmd S n ((P.fetch n).getD .halt)) := by
  show ((List.range P.size).map (fun n => foldCmd S n ((P.fetch n).getD .halt))).toArray[n]? = _
  rw [List.getElem?_toArray, List.getElem?_map,
    List.getElem?_eq_getElem (show n < (List.range P.size).length by simpa using h),
    Option.map_some, List.getElem_range]

theorem run_wellFormed (wf : WellFormed P) : WellFormed (run P S) where
  entry_lt := by rw [run_entry, run_size]; exact wf.entry_lt
  succ_lt := by
    intro n instr s hf hs
    have hn : n < P.size := by have := fetch_lt hf; rwa [run_size] at this
    rw [run_fetch S hn] at hf; injection hf with hf; subst hf
    obtain ⟨c, hc⟩ : ∃ c, P.fetch n = some c := ⟨_, Array.getElem?_eq_getElem hn⟩
    rw [hc, Option.getD_some] at hs
    rw [run_size]; exact wf.succ_lt hc (foldCmd_mem_succs S hs)

/-! ## Behaviour preservation. -/

/-- **Per-step simulation** (identity config): under `CPInv`, each source step is the same step in the
    folded program — a folded `ifz` becomes the `noop` to whichever target the store already forces. -/
theorem step_fold {c c' : Config} (hinv : CPInv S c) (h : Step P c c') : Step (run P S) c c' := by
  have hbf := run_fetch S (P := P) (n := c.node) (by cases h <;> exact fetch_lt ‹_›)
  cases h with
  | @assign nd σ x e next v hf hv =>
      rw [hf] at hbf; simp only [Option.getD_some, foldCmd] at hbf; exact Step.assign hbf hv
  | @ifzT nd σ x z nz hf hz =>
      rw [hf] at hbf; simp only [Option.getD_some, foldCmd] at hbf
      cases hca : constAt S nd x with
      | none => rw [hca] at hbf; exact Step.ifzT hbf hz
      | some cv =>
          have hxcv : σ x = cv := hinv x cv (constAt_sound S hca)
          have hc0 : (cv == 0) = true := beq_iff_eq.mpr (hxcv.symm.trans hz)
          simp only [hca, hc0, if_true] at hbf
          exact Step.noop hbf
  | @ifzF nd σ x z nz hf hz =>
      rw [hf] at hbf; simp only [Option.getD_some, foldCmd] at hbf
      cases hca : constAt S nd x with
      | none => rw [hca] at hbf; exact Step.ifzF hbf hz
      | some cv =>
          have hxcv : σ x = cv := hinv x cv (constAt_sound S hca)
          have hc0 : (cv == 0) = false := beq_eq_false_iff_ne.mpr (hxcv ▸ hz)
          simp only [hca, hc0] at hbf
          exact Step.noop hbf
  | @noop nd σ next hf =>
      rw [hf] at hbf; simp only [Option.getD_some, foldCmd] at hbf; exact Step.noop hbf

theorem steps_fold {σ : Store} {c : Config} (h : Steps P ⟨P.entry, σ⟩ c) :
    Steps (run P S) ⟨P.entry, σ⟩ c := by
  induction h with
  | refl => exact Steps.refl
  | tail hab hbc ih => exact Steps.tail ih (step_fold S (cpInv_run S hab) hbc)

theorem run_final {c : Config} (h : Final P c) : Final (run P S) c := by
  show (run P S).fetch c.node = some .halt
  rw [run_fetch S (fetch_lt h), h]; rfl

theorem run_faulting {c : Config} (h : Faulting P c) : Faulting (run P S) c := by
  obtain ⟨x, e, next, hf, hev⟩ := h
  exact ⟨x, e, next, by rw [run_fetch S (fetch_lt hf), hf]; rfl, hev⟩

/-- **Branch-folding preserves halting** (to the identical terminal store). -/
theorem preserves_halt {σ : Store} {cf : Config}
    (hrun : Steps P ⟨P.entry, σ⟩ cf) (hfin : Final P cf) :
    ∃ df, Steps (run P S) ⟨(run P S).entry, σ⟩ df ∧ Final (run P S) df
        ∧ ∀ v ∈ P.obs, df.store v = cf.store v :=
  ⟨cf, steps_fold S hrun, run_final S hfin, fun _ _ => rfl⟩

/-- **Branch-folding preserves faulting.** -/
theorem preserves_faults {σ : Store} {cf : Config}
    (hrun : Steps P ⟨P.entry, σ⟩ cf) (hfault : Faulting P cf) :
    ∃ df, Steps (run P S) ⟨(run P S).entry, σ⟩ df ∧ Faulting (run P S) df :=
  ⟨cf, steps_fold S hrun, run_faulting S hfault⟩

theorem stepSimG : StepSimG P (run P S) (fun c d => CPInv S c ∧ d = c) := by
  intro c c' d _ hR hstep
  obtain ⟨hinv, rfl⟩ := hR
  exact ⟨c', c', step_fold S hinv hstep, Steps.refl, cpInv_step S hinv hstep, rfl⟩

/-- **Branch-folding preserves divergence.** -/
theorem preserves_diverges (wf : WellFormed P) {σ : Store}
    (hdiv : Diverges P ⟨P.entry, σ⟩) : Diverges (run P S) ⟨(run P S).entry, σ⟩ := by
  rw [run_entry]
  exact diverges_of_stepsimG (stepSimG S) wf wf.entry_lt ⟨cpInv_entry S, rfl⟩ hdiv

end BranchFold
end Pass
end BaseLanguage
